language: r
cache:
  - packages
sudo: required
dist: "xenial"
warnings_are_errors: false

r_packages:
  - covr

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - R CMD INSTALL .
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::codecov()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: true
      local-dir: docs
      on:
        branch: master
